---
# tasks file for apt
- name: apt | update cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: apt | upgrade
  ansible.builtin.apt:
    upgrade: yes
  when: apt_upgrade

- name: apt | install server requirements
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ apt_install_packages }}"

