---
# defaults file for nginx
nginx_remove_default_vhost: true

nginx_vhost_path: /etc/nginx/sites-enabled
nginx_default_vhost_path: /etc/nginx/sites-enabled/default

nginx_kibana_address: http://localhost:5601
