---
# tasks file for kibana
- include_tasks: pre-install.yml

- name: Install Kibana.
  package:
    name: kibana
    state: present

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: true

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana